--- # Author Farkhod Sadykov
-  hosts: mysql-server
   become: all
   become_method: sudo
   connection: ssh
   vars:
     current_password: Redhat2018
     new_password: 1897Bs3J8zj
   tasks:
     - name: Change root user password on first run
       mysql_user: login_user=root login_password={{ current_password }} name=root password={{ new_password }} priv=*.*:ALL,GRANT host={{ item }}
       with_items:
         - $ansible_hostname
         - 127.0.0.1
         - ::1
         - localhost
       ignore_errors: true
       become: yes
